model_list = [
    {
        "script_name": "Devanagari",
        "languages": ["Limbu", 
                    "Marathi", 
                    "Nepali (individual language)", 
                    "Sanskrit", 
                    "Sunwar", 
                    "Eastern Tamang", 
                    "Urdu", 
                    "Baghlayani", 
                    "Bhadrawahi", 
                    "Bilaspuri", 
                    "Chambeali", 
                    "Dogri", 
                    "Gaddi", 
                    "Hariyanvi", 
                    "Hindi", 
                    "Kangri", 
                    "Kulvi", 
                    "Kulvi Outer Seraji", 
                    "Mandeali", 
                    "PahariMahasui",
                    ],
        "model_name": "Devanagari_model",
        "downloaded": True,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Devanagari_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": True,
        "accuracy": "99.05%",
    },
    {
        "script_name": "Arabic",
        "languages": ["Standard Arabic", 
                    "Central Kurdish", 
                    "Gilaki", 
                    "Iranian Persian", 
                    "Sanskrit", 
                    "Susu", 
                    "Uighur", 
                    "Urdu", 
                    ],
        "model_name": "Arabic_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Arabic_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "99.79%",
    },
    {
        "script_name": "Bengali",
        "languages": ["Assamese", 
                    "Bengali", 
                    "Sanskrit", 
                    ],
        "model_name": "Bengali_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Bengali_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "99.81%",
    },
    {
        "script_name": "Cyrillic",
        "languages": ["Belarusian", 
                    "Romanian", 
                    "Russian",
                    "Tajik", 
                    "Uighur", 
                    "Ukrainian", 
                    ],
        "model_name": "Cyrillic_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Cyrillic_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "99.67%",
    },
    {
        "script_name": "Ethiopic",
        "languages": ["Dawro", 
                    "Gamo", 
                    "Gofa",
                    "Male (Ethiopia)", 
                    ],
        "model_name": "Ethiopic_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Ethiopic_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(2, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "98.33%",
    },
    {
        "script_name": "Gujarati",
        "languages": ["Gujarati", 
                    "Sanskrit", 
                    ],
        "model_name": "Gujarati_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Gujarati_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "99.89%",
    },
    {
        "script_name": "Gurmukhi",
        "languages": ["Panjabi", 
                    "Sanskrit", 
                    ],
        "model_name": "Gurmukhi_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Gurmukhi_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "99.89%",
    },
    {
        "script_name": "Hebrew",
        "languages": ["Ancient Hebrew", 
                    "Hebrew", 
                    ],
        "model_name": "Hebrew_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Hebrew_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "100%",
    },
    {
        "script_name": "Latin",
        "languages": ["Arifama-Miniafia", 
                    "Ankave", 
                    "Abau", 
                    "Amarasi", 
                    "Ambulas", 
                    "Inabaknon", 
                    "Aneme Wake", 
                    "Saint Lucian Creole French", 
                    "Achi", 
                    "Achuar-Shiwiar", 
                    "Adzera", 
                    "Eastern Arrernte", 
                    "Amele", 
                    "Agarabi", 
                    "Angor", 
                    "Angaataha", 
                    "Agutaynen", 
                    "Aguaruna", 
                    "Central Cagayan Agta", 
                    "Aguacateco", 
                    "Arosi", 
                    "Akan", 
                    "Akawaio", 
                    "Alune", 
                    "Algonquin", 
                    "Tosk Albanian", 
                    "Alyawarr", 
                    "Yanesha'", 
                    "Hamer-Banna", 
                    "Ambai", 
                    "Ama (Papua New Guinea)", 
                    "Amanab", 
                    "Amo", 
                    "Alamblak", 
                    "Amarakaeri", 
                    "Guerrero Amuzgo", 
                    "Anmatyerre", 
                    "Nend", 
                    "Denya", 
                    "Anindilyakwa", 
                    "Mufian", 
                    "Ömie", 
                    "Bumbita Arapesh", 
                    "Sa'a", 
                    "Bukiyip", 
                    "Apinayé", 
                    "Arop-Lokep", 
                    "Apurinã", 
                    "Western Apache", 
                    "Safeyoka", 
                    "Western Arrarnta", 
                    "Arabela", 
                    "Mapudungun", 
                    "Arapaho", 
                    "Dano", 
                    "Pele-Ata", 
                    "Zaiwa", 
                    "Ata Manobo", 
                    "Ivbie North-Okpela-Arhe", 
                    "Pamplona Atta", 
                    "Waorani", 
                    "Anuki", 
                    "Awiyaana", 
                    "Au", 
                    "Awa (Papua New Guinea)", 
                    "Awabakal", 
                    "Awara", 
                    "South Azerbaijani", 
                    "San Pedro Amuzgos Amuzgo", 
                    "Highland Puebla Nahuatl", 
                    "Waimaha", 
                    "Baatonum", 
                    "Barai", 
                    "Girawa", 
                    "Bariai", 
                    "Kaluli", 
                    "Bunama", 
                    "Beaver", 
                    "Benabena", 
                    "Beami", 
                    "Blagar", 
                    "Tagabawa", 
                    "Bughotu", 
                    "Binandere", 
                    "Bimin", 
                    "Biangai", 
                    "Barok", 
                    "Fanamaket", 
                    "Binumarien", 
                    "Bedjond", 
                    "Baruga", 
                    "Binukid", 
                    "Baki", 
                    "Bakairí", 
                    "Baikeno", 
                    "Siksika", 
                    "Balangao", 
                    "Balantak", 
                    "Kein", 
                    "Ghayavi", 
                    "Muinane", 
                    "Somba-Siawari", 
                    "Bola", 
                    "Bora", 
                    "Anjam", 
                    "Bine", 
                    "Buamu", 
                    "Koronadal Blaan", 
                    "Sarangani Blaan", 
                    "Boko (Benin)", 
                    "Busa", 
                    "Breton", 
                    "Bangwinji", 
                    "Barasana-Eduria", 
                    "Baga Sitemu", 
                    "Akoose", 
                    "Bugawac", 
                    "Bokobaru", 
                    "Baeggu", 
                    "Burarra", 
                    "Buhutu", 
                    "Baruya", 
                    "Qaqet", 
                    "Bribri", 
                    "Mapos Buang", 
                    "Belize Kriol English", 
                    "Chortí", 
                    "Garifuna", 
                    "Chuj", 
                    "Southern Carrier", 
                    "Kaqchikel", 
                    "Chácobo", 
                    "Chipaya", 
                    "Galibi Carib", 
                    "Cavineña", 
                    "Chiquitano", 
                    "Carapana", 
                    "Chachi", 
                    "Chavacano", 
                    "Cashibo-Cacataibo", 
                    "Cashinahua", 
                    "Chayahuita", 
                    "Candoshi-Shapra", 
                    "Cacua", 
                    "Comaltepec Chinantec", 
                    "Cebuano", 
                    "Eastern Khumi Chin", 
                    "Czech", 
                    "Kagayanen", 
                    "Chamorro", 
                    "Highland Oaxaca Chontal", 
                    "Tabasco Chontal", 
                    "Chuukese", 
                    "Quiotepec Chinantec", 
                    "Ozumacín Chinantec", 
                    "Ashéninka Pajonal", 
                    "Chuave", 
                    "Lealao Chinantec", 
                    "Caluyanun", 
                    "Cerma", 
                    "Asháninka", 
                    "Lalana Chinantec", 
                    "Tepetotutla Chinantec", 
                    "Colorado", 
                    "Cofán", 
                    "Caquinte", 
                    "Palantla Chinantec", 
                    "Ucayali-Yurúa Ashéninka", 
                    "Ajyíninka Apurucayali", 
                    "Pichis Ashéninka", 
                    "South Ucayali Ashéninka", 
                    "El Nayar Cora", 
                    "Carrier", 
                    "Sochiapam Chinantec", 
                    "Siyin Chin", 
                    "Tataltepec Chatino", 
                    "Thaiphum Chin", 
                    "Western Highland Chatino", 
                    "Chol", 
                    "Cubeo", 
                    "Usila Chinantec", 
                    "Cuiba", 
                    "San Blas Kuna", 
                    "Teutila Cuicatec", 
                    "Tepeuxila Cuicatec", 
                    "Kwere", 
                    "Nopala Chatino", 
                    "Dangaléat", 
                    "Marik", 
                    "Gwahatike", 
                    "Danish", 
                    "Dedua", 
                    "German", 
                    "Casiguran Dumagat Agta", 
                    "Dogrib", 
                    "Daga", 
                    "Dhangu-Djangu", 
                    "Dieri", 
                    "Southwestern Dinka", 
                    "Djinang", 
                    "Eastern Maroon Creole", 
                    "Djambarrpuyngu", 
                    "Dobu", 
                    "Lukpa", 
                    "Dombe", 
                    "Dawro", 
                    "Dawawa", 
                    "Dhuwaya", 
                    "Eastern Bontok", 
                    "Koti", 
                    "Mussau-Emira", 
                    "Northern Emberá", 
                    "English", 
                    "Enga", 
                    "Esperanto", 
                    "Ogea", 
                    "Ese Ejja", 
                    "Northwest Alaska Inupiatun", 
                    "Edolo", 
                    "Ewe", 
                    "Fasu", 
                    "Faiwol", 
                    "Fataleka", 
                    "Maasina Fulfulde", 
                    "Fore", 
                    "French", 
                    "Borgu Fulfulde", 
                    "Pular", 
                    "Western Niger Fulfulde", 
                    "Alekano", 
                    "Borei", 
                    "Kandawo", 
                    "Nobonob", 
                    "Umanakaina", 
                    "Wipi", 
                    "Kire", 
                    "Patpatar", 
                    "Guhu-Samane", 
                    "Gamo", 
                    "Ngangam", 
                    "Gumatj", 
                    "Western Bolivian Guaraní", 
                    "Gofa", 
                    "Guajajára", 
                    "Guahibo", 
                    "Eastern Bolivian Guaraní", 
                    "Sea Island Creole English", 
                    "Guambiano", 
                    "Mbyá Guaraní", 
                    "Guayabero", 
                    "Gunwinggu", 
                    "Gourmanchéma", 
                    "Guanano", 
                    "Golin", 
                    "Kuku-Yalanji", 
                    "Gumawana", 
                    "Gwichʼin", 
                    "Ngäbere", 
                    "Guarayu", 
                    "Haitian", 
                    "Hausa", 
                    "Hawaiian", 
                    "Huichol", 
                    "Hixkaryána", 
                    "Halia", 
                    "Matu Chin", 
                    "Hiri Motu", 
                    "Caribbean Hindustani", 
                    "Hopi", 
                    "Hote", 
                    "Croatian", 
                    "Minica Huitoto", 
                    "Huambisa", 
                    "Huli", 
                    "Hungarian", 
                    "Huastec", 
                    "Murui Huitoto", 
                    "San Mateo Del Mar Huave", 
                    "Sabu", 
                    "Iatmul", 
                    "Ignaciano", 
                    "Ika", 
                    "Ikwere", 
                    "Iloko", 
                    "Imbongu", 
                    "Inga", 
                    "Indonesian", 
                    "Inoke-Yate", 
                    "Tuma-Irumu", 
                    "Ipili", 
                    "Isanzu", 
                    "Italian", 
                    "Sepik Iwam", 
                    "Ixil", 
                    "Popti'", 
                    "Yabem", 
                    "Yanyuwa", 
                    "Tol", 
                    "Bu (Kaduna State)", 
                    "Shuar", 
                    "Janji", 
                    "Caribbean Javanese", 
                    "Capanahua", 
                    "Kadiwéu", 
                    "Camsá", 
                    "Iwal", 
                    "Kamano", 
                    "Kutu", 
                    "Makonde", 
                    "Tsikimba", 
                    "Kekchí", 
                    "Kenyang", 
                    "West Kewa", 
                    "Kube", 
                    "Kaiwá", 
                    "Kaingang", 
                    "Kasua", 
                    "Keapara", 
                    "Kikuyu", 
                    "Northeast Kiwai", 
                    "Kisi", 
                    "Kisar", 
                    "Kunjen", 
                    "East Kewa", 
                    "Odoodee", 
                    "Kosarek Yale", 
                    "Nukna", 
                    "Maskelynes", 
                    "Kâte", 
                    "Kalam", 
                    "Limos Kalinga", 
                    "Kwoma", 
                    "Kamasau", 
                    "Kanite", 
                    "Kankanaey", 
                    "Mankanya", 
                    "Western Kanjobal", 
                    "Tabo", 
                    "Kosraean", 
                    "Komba", 
                    "Kapingamarangi", 
                    "Karajá", 
                    "Korafe-Yegha", 
                    "Kobon", 
                    "Mountain Koiali", 
                    "Mum", 
                    "Doromu-Koki", 
                    "Kakabai", 
                    "Kyenele", 
                    "Kandas", 
                    "Kuanua", 
                    "Uare", 
                    "Borong", 
                    "Kurti", 
                    "Kuot", 
                    "'Auhelawa", 
                    "Kuman (Papua New Guinea)", 
                    "Kunimaipa", 
                    "Kuni-Boazi", 
                    "Border Kuna", 
                    "Kwaio", 
                    "Kwara'ae", 
                    "Awa-Cuaiquer", 
                    "Kwanga", 
                    "Kyaka", 
                    "Kouya", 
                    "Keyagana", 
                    "Kenga", 
                    "Kayabí", 
                    "Kosena", 
                    "Lacandon", 
                    "Latin", 
                    "Label", 
                    "Central Bontok", 
                    "Tungag", 
                    "Kara (Papua New Guinea)", 
                    "Luang", 
                    "Wala", 
                    "Nyindrou", 
                    "Lingala", 
                    "Lithuanian", 
                    "Lole", 
                    "Ganda", 
                    "Luo (Kenya and Tanzania)", 
                    "Lewo", 
                    "San Jerónimo Tecóatl Mazatec", 
                    "Jalapa De Díaz Mazatec", 
                    "Mam", 
                    "Chiquihuitlán Mazatec", 
                    "Huautla Mazatec", 
                    "Sateré-Mawé", 
                    "Central Mazahua", 
                    "Western Bukidnon Manobo", 
                    "Macushi", 
                    "Mangseng", 
                    "Nadëb", 
                    "Maxakalí", 
                    "Sarangani Manobo", 
                    "Matigsalug Manobo", 
                    "Maca", 
                    "Machiguenga", 
                    "Sharanahua", 
                    "Matsés", 
                    "Coatlán Mixe", 
                    "Makaa", 
                    "Ese", 
                    "Menya", 
                    "Melpa", 
                    "Mengen", 
                    "Mekeo", 
                    "Merey", 
                    "Mato", 
                    "Motu", 
                    "Morokodo", 
                    "Makhuwa-Meetto", 
                    "Matumbi", 
                    "Mauwake", 
                    "Atatláhuca Mixtec", 
                    "Mi'kmaq", 
                    "Ocotepec Mixtec", 
                    "San Miguel El Grande Mixtec", 
                    "Chayuco Mixtec", 
                    "Peñoles Mixtec", 
                    "Pinotepa Nacional Mixtec", 
                    "Isthmus Mixe", 
                    "Southern Puebla Mixtec", 
                    "Coatzospan Mixtec", 
                    "San Juan Colorado Mixtec", 
                    "Mokilese", 
                    "Mokole", 
                    "Kupang Malay", 
                    "Silacayoapan Mixtec", 
                    "Manambu", 
                    "Mape", 
                    "Bargam", 
                    "Mangga Buang", 
                    "Madak", 
                    "Mbula", 
                    "Mopán Maya", 
                    "Molima", 
                    "Maung", 
                    "Martu Wangka", 
                    "Yosondúa Mixtec", 
                    "Migabac", 
                    "Dadibi", 
                    "Mian", 
                    "Misima-Panaeati", 
                    "Mbuko", 
                    "Mamasa", 
                    "Masbatenyo", 
                    "Sankaran Maninka", 
                    "Mansaka", 
                    "Agusan Manobo", 
                    "Aruamu", 
                    "Maiwa (Papua New Guinea)", 
                    "Totontepec Mixe", 
                    "Bo-Ung", 
                    "Muyang", 
                    "Manam", 
                    "Minaveha", 
                    "Are", 
                    "Mwera (Chimwera)", 
                    "Murrinh-Patha", 
                    "Kala Lagaw Ya", 
                    "Tezoatlán Mixtec", 
                    "Tlahuitoltepec Mixe", 
                    "Juquila Mixe", 
                    "Jamiltepec Mixtec", 
                    "Mamara Senoufo", 
                    "Mundurukú", 
                    "Muyuw", 
                    "Macuna", 
                    "Maiadomu", 
                    "Southern Nambikuára", 
                    "Nabak", 
                    "Nakanai", 
                    "Naasioi", 
                    "Ngarrindjeri", 
                    "Nggem", 
                    "Iyo", 
                    "Central Huasteca Nahuatl", 
                    "Northern Puebla Nahuatl", 
                    "Michoacán Nahuatl", 
                    "Chumburung", 
                    "Ndengereko", 
                    "Ndamba", 
                    "Dhao", 
                    "Ngulu", 
                    "Guerrero Nahuatl", 
                    "Eastern Huasteca Nahuatl", 
                    "Tetelcingo Nahuatl", 
                    "Zacatlán-Ahuacatlán-Tepetzintla Nahuatl", 
                    "Takuu", 
                    "Naro", 
                    "Noone", 
                    "Western Huasteca Nahuatl", 
                    "Northern Oaxaca Nahuatl", 
                    "Nek", 
                    "Nii", 
                    "Ninzo", 
                    "Nkonya", 
                    "Dutch", 
                    "Gela", 
                    "Nimoa", 
                    "Nyangumarta", 
                    "Ngindo", 
                    "Woun Meu", 
                    "Numanggang", 
                    "Nomatsiguenga", 
                    "Ewage-Notu", 
                    "Southeastern Puebla Nahuatl", 
                    "Nehan", 
                    "Nali", 
                    "Ngaanyatjarra", 
                    "Northern Tepehuan", 
                    "Natügu", 
                    "Nunggubuyu", 
                    "Namiae", 
                    "Southwest Tanna", 
                    "Nyanja", 
                    "Nyungar", 
                    "Nyungwe", 
                    "Obo Manobo", 
                    "Orokaiva", 
                    "South Tairora", 
                    "Olo", 
                    "Ono", 
                    "Tohono O'odham", 
                    "Oksapmin", 
                    "Mezquital Otomi", 
                    "Eastern Highland Otomi", 
                    "Tenango Otomi", 
                    "Querétaro Otomi", 
                    "Estado de México Otomi", 
                    "Parecís", 
                    "Paumarí", 
                    "Tenharim", 
                    "Northern Paiute", 
                    "Yine", 
                    "Piapoco", 
                    "Piratapuyo", 
                    "Pintupi-Luritja", 
                    "Pitjantjatjara", 
                    "San Marcos Tlacoyalco Popoloca", 
                    "Palikúr", 
                    "Paama", 
                    "San Juan Atzingo Popoloca", 
                    "Poqomchi'", 
                    "Highland Popoluca", 
                    "Polish", 
                    "Pohnpeian", 
                    "Portuguese", 
                    "Pogolo", 
                    "Folopa", 
                    "Paranan", 
                    "Paicî", 
                    "Patep", 
                    "Bambam", 
                    "Gapapaiwa", 
                    "Huallaga Huánuco Quechua", 
                    "K'iche'", 
                    "Lambayeque Quechua", 
                    "South Bolivian Quechua", 
                    "North Bolivian Quechua", 
                    "Southern Pastaza Quechua", 
                    "Cajamarca Quechua", 
                    "Eastern Apurímac Quechua", 
                    "Huamalíes-Dos de Mayo Huánuco Quechua", 
                    "Margos-Yarowilca-Lauricocha Quechua", 
                    "North Junín Quechua", 
                    "San Martín Quechua", 
                    "Huaylla Wanca Quechua", 
                    "Northern Pastaza Quichua", 
                    "Huaylas Ancash Quechua", 
                    "Panao Huánuco Quechua", 
                    "Northern Conchucos Ancash Quechua", 
                    "Southern Conchucos Ancash Quechua", 
                    "Ramoaaina", 
                    "Kara (Tanzania)", 
                    "Ringgou", 
                    "Rikbaktsa", 
                    "Carpathian Romani", 
                    "Vlax Romani", 
                    "Romanian", 
                    "Rotokas", 
                    "Kriol", 
                    "Dela-Oenale", 
                    "Waima", 
                    "Luguru", 
                    "Roviana", 
                    "Rawa", 
                    "Buglere", 
                    "Sanskrit", 
                    "Saliba", 
                    "Safwa", 
                    "Subiya", 
                    "Sena", 
                    "Secoya", 
                    "Mag-antsi Ayta", 
                    "Sursurunga", 
                    "Shatt", 
                    "Shipibo-Conibo", 
                    "Mende (Papua New Guinea)", 
                    "Epena", 
                    "Salt-Yui", 
                    "Bolinao", 
                    "Sinaugoro", 
                    "Siona", 
                    "Siane", 
                    "Sam", 
                    "Saniyo-Hiyewe", 
                    "Somali", 
                    "Kanasi", 
                    "Miyobe", 
                    "Spanish", 
                    "Selepet", 
                    "Akukem", 
                    "Supyire Senoufo", 
                    "Saposa", 
                    "Sabaot", 
                    "Siriano", 
                    "Saramaccan", 
                    "Sranan Tongo", 
                    "Serbian", 
                    "Sirionó", 
                    "Siroi", 
                    "Seimat", 
                    "Samberigi", 
                    "Southeastern Tepehuan", 
                    "Sulka", 
                    "Suena", 
                    "Susu", 
                    "Swedish", 
                    "Swahili (individual language)", 
                    "Suau", 
                    "Suba", 
                    "Lowland Tarahumara", 
                    "Tatuyo", 
                    "Tai", 
                    "Takia", 
                    "Mandara", 
                    "North Tairora", 
                    "Tboli", 
                    "Tawala", 
                    "Ditammari", 
                    "Ticuna", 
                    "Torres Strait Creole", 
                    "Thado Chin", 
                    "Tetun Dili", 
                    "Huehuetla Tepehua", 
                    "Tereno", 
                    "Tetum", 
                    "Tewa (USA)", 
                    "Teribe", 
                    "Tagalog", 
                    "Sudest", 
                    "Tangoa", 
                    "Kuuk Thaayorre", 
                    "Tifal", 
                    "Timbe", 
                    "Tiwi", 
                    "Tiruray", 
                    "Takwane", 
                    "Upper Necaxa Totonac", 
                    "Telefol", 
                    "Haruai", 
                    "Tacana", 
                    "Tanimuca-Retuarã", 
                    "Kwamera", 
                    "North Tanna", 
                    "Whitesands", 
                    "Coyutla Totonac", 
                    "Toma", 
                    "Gizrra", 
                    "Tojolabal", 
                    "Tonga (Tonga Islands)", 
                    "Xicotepec De Juárez Totonac", 
                    "Papantla Totonac", 
                    "Highland Totonac", 
                    "Taupota", 
                    "Tok Pisin", 
                    "Tlachichilco Tepehua", 
                    "Tinputz", 
                    "Copala Triqui", 
                    "Tsishingini", 
                    "Tektiteko", 
                    "Bwanabwana", 
                    "Mutu", 
                    "Tuyuca", 
                    "Central Tunebo", 
                    "Tucano", 
                    "Turkish", 
                    "Southeast Ambrym", 
                    "Twi", 
                    "Tii", 
                    "Kayapó", 
                    "Tz'utujil", 
                    "Tzotzil", 
                    "Ubir", 
                    "Umbu-Ungu", 
                    "Uduk", 
                    "Uighur", 
                    "Ulithian", 
                    "Meriam Mir", 
                    "Uripiv-Wala-Rano-Atchin", 
                    "Urarina", 
                    "Urubú-Kaapor", 
                    "Urdu", 
                    "Urim", 
                    "Urat", 
                    "Sop", 
                    "Usarufa", 
                    "Uspanteco", 
                    "Uri", 
                    "Lote", 
                    "Vidunda", 
                    "Vietnamese", 
                    "Iduna", 
                    "Ayautla Mazatec", 
                    "Waffa", 
                    "Wolaytta", 
                    "Wapishana", 
                    "Kaninuwa", 
                    "Vwanji", 
                    "Warlpiri", 
                    "Wedau", 
                    "Weri", 
                    "Wik-Mungkan", 
                    "Wiru", 
                    "Vitu", 
                    "Walmajarri", 
                    "Mwani", 
                    "Wantoat", 
                    "Usan", 
                    "Wolof", 
                    "Hanga Hundi", 
                    "Garrwa", 
                    "Worrorra", 
                    "Waris", 
                    "Waskia", 
                    "Wuvulu-Aua", 
                    "Xavánte", 
                    "Kombio", 
                    "Hdi", 
                    "Kamula", 
                    "Northern Kankanay", 
                    "Konkomba", 
                    "Sio", 
                    "Diuxi-Tilantongo Mixtec", 
                    "Magdalena Peñasco Mixtec", 
                    "Yaminahua", 
                    "Yagua", 
                    "Yalunka", 
                    "Yapese", 
                    "Yaqui", 
                    "Yaweyuha", 
                    "Yucuna", 
                    "Yakan", 
                    "Yele", 
                    "Iamalele", 
                    "Yongkom", 
                    "Yoruba", 
                    "Yareba", 
                    "Yaouré", 
                    "Yessan-Mayo", 
                    "Karkar-Yuri", 
                    "Yopno", 
                    "Yau (Morobe Province)", 
                    "Yawa", 
                    "Sierra de Juárez Zapotec", 
                    "Western Tlacolula Valley Zapotec", 
                    "Ocotlán Zapotec", 
                    "Cajonos Zapotec", 
                    "Isthmus Zapotec", 
                    "Zaramo", 
                    "Miahuatlán Zapotec", 
                    "Ozolotepec Zapotec", 
                    "Zapotec", 
                    "Rincón Zapotec", 
                    "Santo Domingo Albarradas Zapotec", 
                    "Tabaa Zapotec", 
                    "Yatzachi Zapotec", 
                    "Mitla Zapotec", 
                    "Coatecas Altas Zapotec", 
                    "Kinga", 
                    "Zia", 
                    "Zigula", 
                    "Malay (individual language)", 
                    "Francisco León Zoque", 
                    "Choapan Zapotec", 
                    "Lachixío Zapotec", 
                    "Mixtepec Zapotec", 
                    "Amatlán Zapotec", 
                    "Zoogocho Zapotec", 
                    "Yalálag Zapotec", 
                    "Chichicapan Zapotec", 
                    "Texmelucan Zapotec", 
                    "Southern Rincon Zapotec", 
                    "Quioquitani-Quierí Zapotec", 
                    "Yatee Zapotec", 
                    "Zyphe Chin", 
                    ], 
        "model_name": "Latin_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Latin_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "98.15%",
    },
    {
        "script_name": "Malayalam",
        "languages": ["Malayalam", 
                    "Sanskrit", 
                    ],
        "model_name": "Malayalam_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Malayalam_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "99.59%",
    },
    {
        "script_name": "Myanmar",
        "languages": ["Burmese", 
                    "Sanskrit", 
                    ],
        "model_name": "Myanmar_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Myanmar_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "99.96%",
    },
    {
        "script_name": "Oriya",
        "languages": ["Odiya", 
                    "Sanskrit", 
                    ],
        "model_name": "Oriya_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Oriya_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "99.94%",
    },
    {
        "script_name": "Tamil",
        "languages": ["Tamil", 
                    "Sanskrit", 
                    ],
        "model_name": "Tamil_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Tamil_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "99.94%",
    },
    {
        "script_name": "Telugu",
        "languages": ["Telugu", 
                    "Sanskrit", 
                    ],
        "model_name": "Telugu_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Telugu_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "99.94%",
    },
    {
        "script_name": "Thai",
        "languages": ["Thai", 
                    "Sanskrit", 
                    ],
        "model_name": "Thai_model",
        "downloaded": False,
        "model_type": "Multinomial Naive Bayes",
        "vectorizer_model_name": "Thai_vectorizer",
        "vectorizer_type": "CountVectorizer",
        "vectorizer_params": {
            "ngram_range": "(3, 3)",
            "max_features": 2000,
            "analyzer": "char"
        },
        "vectorizer_downloaded": False,
        "accuracy": "100%",
    },
]
